include: package:lints/recommended.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "example/misskey_dart_flutter_app_example/**"
linter:
  rules:
    - directives_ordering
