include: package:lints/recommended.yaml
analyzer:
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "example/misskey_dart_flutter_app_example/**"
linter:
  rules:
    - directives_ordering
    - empty_container_bodies
    - unnecessary_const_in_enum_constructor
    - unnecessary_type_name_in_constructor
