targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          include:
            - "lib/**/*.dart"
        options:
          checked: true
          explicit_to_json: true
    sources:
          exclude:
            - example/**