name: misskey_dart
description: Misskey API wrapper
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.11
  dotenv: ^4.2.0
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.8
  uuid: ^4.4.2
dependencies:
  collection: ^1.18.0
  dio: ^5.5.0+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  web_socket_channel: ^3.0.1
