name: misskey_dart
description: Misskey API wrapper
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.13.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.16.1
  dotenv: ^4.2.0
  freezed: ^4.0.2
  json_serializable: ^6.14.1
  lints: ^6.1.0
  test: ^1.32.0
  uuid: ^4.6.0
dependencies:
  collection: ^1.19.1
  dio: ^5.11.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  path: ^1.9.1
  web_socket_channel: ^3.0.3
