name: misskey_dart
description: Misskey API wrapper
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=3.7.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.15
  dotenv: ^4.2.0
  freezed: ^2.5.8
  json_serializable: ^6.9.4
  lints: ^5.1.1
  test: ^1.25.15
  uuid: ^4.5.1
dependencies:
  collection: ^1.19.1
  dio: ^5.8.0+1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.1
  web_socket_channel: ^3.0.2
